defaults:
  - gen4

name: gen4_extended_sample
path: /home/oeoiewt/eTraM/rvt_eTram/data/gen4_cls8_extended_sample

# Extended sample configuration
extended_sample: true
sample_size: 45
coverage_target: 0.15  # ~15% of full dataset objects

# Training optimizations for extended dataset
batch_optimization: true
sequence_balancing: true
